### ISSUE TITLE
site-health error

### ISSUE THREAD

**Issue by thomascenni** [aaemnnosttv/wp-sqlite-db#38] opened 2022-09-10 13:55 UTC
Hi,
Accessing the page /wp-admin/site-health.php I got this error:

![Screen Shot 2022-09-10 at 10 54 49](https://user-images.githubusercontent.com/33039107/189486586-01a971a4-57c9-47f0-b8b9-02b78209f6f5.png)

**Comment by kk6mrp** [comment] 2022-09-10 14:10
Did you notice this issue? https://github.com/aaemnnosttv/wp-sqlite-db/issues/24

**Comment by thomascenni** [comment] 2022-09-10 15:26
No, it's clearly a duplicate, thanks.

**Comment by aaemnnosttv** [comment] 2023-02-05 17:06
Closing as a duplicate of #24 which has also been resolved.

**Closed by aaemnnosttv** 2023-02-05 17:06 UTC
